### PR TITLE
Mockito 5

### PR DESCRIPTION
**Pull request by cheeseng**
Updated to use mockito 5.8.0, and added a note in README.md about the requirement for jdk11 for mockito 5.

### CODE REVIEW

**Comment by LuciferYang** [comment]
https://github.com/scalatest/scalatestplus-mockito/blob/0e869cadf95f4188f0f652d684a8e975590c3e3c/.github/workflows/ci.yml#L15

Need to switch to installing Java 11.

**Comment by cheeseng** [comment]
> https://github.com/scalatest/scalatestplus-mockito/blob/0e869cadf95f4188f0f652d684a8e975590c3e3c/.github/workflows/ci.yml#L15
> 
> Need to switch to installing Java 11.

Yup, you're right, CI passed now, thanks.

**Comment by DieBauer** [comment]
Any plans on this? The official site already advertises this, but the artifact doesn't exist: 
https://www.scalatest.org/plus/mockito 
`libraryDependencies += "org.scalatestplus" %% "mockito-5-6" % "3.2.17.0" % "test"`

**Comment by cheeseng** [comment]
@DieBauer I am sorry we overlooked this and I think the previously staged artifacts for mockito 5.6 was dropped automatically, I have re-staged with latest mockito 5.8 and hopefully @bvenners shall release it soon!

**Comment by DieBauer** [comment]
Thanks for the update, and effort :)

**Review by bvenners — APPROVED** [review]

**Comment by LuciferYang** [comment]
It looks like need to update the PR description. The current PR description is still `Updated to use mockito 5.6.0`.

**Comment by cheeseng** [comment]
@LuciferYang Thanks for the kind reminder.

And the good news is @bvenners has just released the artifacts!

**Comment by Martomate** [comment]
Hello! Just so you know, the website still mentions 5.6 instead of 5.8 (https://www.scalatest.org/plus/mockito). Would be nice if it was updated.

**Comment by cheeseng** [comment]
@Martomate Thanks for the reminder, I have submitted the following PR for it: 

https://github.com/scalatest/scalatest-website/pull/235

Cheers.

**Pull request merged**
